### ISSUE TITLE
Timezone switching seems to be broken.

### ISSUE THREAD

**Issue by romalytvynenko** [RebelCode/bookings-js#7]
When the page is refreshed, the browser parses the date wrongly, so it appears different to how it was when the user saved the download.

Also, calendar is applying local timezone and it looks like broken.

**Comment by markzahra** [comment]
I believe the description of this issue should read:

When a Nedit Download page is refreshed, the browser parses the date in the timezone selector wrongly. Therefore, it appears differently to how it was when the user saved the download.

Also, in the availability calendar in the Bookings meta box of the Nedit Download page, changing the timezone from the dropdown does not change the times rendered in the availability calendar.

**Comment by romalytvynenko** [comment]
@markzahra, one small detail.

In the availability calendar in the Bookings meta box of the Nedit Download page, when you're changing the timezone, it shouldn't change times on availabilities in the calendar. Instead, visible times on availabilities will remain, *but* when availabilities will be saved, it will be saved in UTC with that timezone shift.

**Comment by romalytvynenko** [comment]
fixed in https://github.com/RebelCode/bookings-js/pull/8

**Comment by mecha** [comment]
@romalytvynenko The timezone is meant to shift the availabilities. If I have an availability from 10:00 till 12:00 and the current timezone is UTC+2 (for example), if I change the timezone to example UTC+5, then the rules should move by 3 hours. In the case of this example, the rule becomes 13:00 till 15:00.

The very purpose of this option to allow the user to enter the availability times in whatever timezone they are comfortable with, or whatever is appropriate for that service. When the availability data is sent to the backend, it will be in ISO8601 format: `2018-05-18T13:00:00+05:00`. The server parses this into a unix timestamp and saves it.

Currently, the server gives all time in UTC. But this should not be assumed anyway because all date times are given in ISO8601, and since the timezone is included in that format, the client-side should have the correct time automatically, without any assumptions. But when rendering them in the availability calendar, the service timezone is added to those date times to render them in that timezone.

I hope this clear. If not, I'll try and explain it differently.

**Comment by markzahra** [comment]
As Roman explained in a Skype call, rendering of times in availability calendar will not shift when changing availability timezone. This is due to the issues it will cause with "All day" availabilities and those with certain repeating options.

For this reason, the availability calendar will display the new timezone under the available times on each day,  but only hen the timezone selected is not the website's timezone.

**Comment by mecha** [comment]
Agreed. The client should still indicate the timezone in the ISO8601 date time strings, and process date time strings from the server accordingly.
